### ISSUE TITLE
Known bug: Issue displaying the right colours

### ISSUE THREAD

**Issue by KvasirSG** [KvasirSG/LucidNightmareHelper#2]
![image](https://user-images.githubusercontent.com/12102444/166158126-ca6a6158-44a5-46e0-ba59-50e321b7020f.png)

the buttons place a colour ring around the floor but the colours do not match the ring it places.

**Comment by Chaseworld** [comment]
Hello. I was wondering if there was going to be a working version of this for the latest patch on World of Warcraft? Thank you for your time.
