### ISSUE TITLE
10.0 UI changes

### ISSUE THREAD

**Issue by KvasirSG** [KvasirSG/LucidNightmareHelper#3]
Hello. I was wondering if there was going to be a working version of this for the latest patch on World of Warcraft? Thank you for your time.

_Originally posted by @Chaseworld in https://github.com/KvasirSG/LucidNightmareHelper/issues/2#issuecomment-1338371717_

Due to the UI changes that happened in 10.0 of Dragonflight the addon need a major rewrite in all of the UI components in order to work. I have not looked into the new changes and it would likely take me some time to make a working version of the addon with the limited time I have available already.

**Comment by Chaseworld** [comment]
I wouldn't mind if it took a while. I just wanted to see if it would be possible. Thank you for looking at my comment!

**Comment by KvasirSG** [comment]
Still having some issues with the frames but I got a somewhat working version 
https://github.com/KvasirSG/LucidNightmareHelper/releases/tag/v0.2.1
